### ISSUE TITLE
English(US) voice can't patch and replace new .pck 

### ISSUE THREAD

**Issue by prpjzz** [GamerYuan/GenshinPatcher#1]
I think this error happen because folder English(US) contains symbol "(" and ")", and command script not have quotations marks for English(US) folder

Thank you ~

**Comment by GamerYuan** [comment]
Mind if you share the error message?

Currently the patch logic runs with the following line (line):
`"!WorkingDirForAdmin!hpatchz.exe" -f "!WorkingDirForAdmin!%%i" "!WorkingDirForAdmin!%%i.hdiff" "!WorkingDirForAdmin!%%i"`

Quotation marks are in place to account for the brackets, and our in-house testing shows no issue with the patching process (across all available packages). Should there be a fault on the script we would fix it as soon as possible

Thanks a bunch!

**Comment by TohLiYuan** [comment]
> I think this error happen because folder English(US) contains symbol "(" and ")", and command script not have quotations marks for English(US) folder
> 
> Thank you ~

@prpjzz Tagging in case the notification on the previous reply doesn't go through!

**Comment by GamerYuan** [comment]
@prpjzz Tagging in case the notification didn't go through!

**Comment by GamerYuan** [comment]
Hello there! As you haven't given any replies to how the error can be recreated, I will be closing the issue. Please attach the steps to recreate the issue when you reopen the issue so that we could start the debugging process.

**Comment by prpjzz** [comment]
I think i know that the problem. When I copy file from hdifffiles.txt and deletefiles.txt, I forgot modify from forward slash to back slash 🤣🤣🤣🤣. I ran script this after modify, and everything is working probably.

**Comment by GamerYuan** [comment]
Glad everything is working fine. As a side note you can always use the pre-processed zip files that we provide on every version update to patch the game hassle free. Cheers!
